routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

$methods = ['index', 'create', 'store',];
Route::resource('deposits', 'DepositController')
    ->only($methods)
    ->names('deposits');

$methods = ['index',];
Route::resource('transactions', 'TransactionController')
    ->only($methods)
    ->names('transactions');

Route::get('/wallet/top-up', 'WalletController@createTopUp')->name('wallets.top-up.create');
Route::post('/wallet/top-up', 'WalletController@storeTopUp')->name('wallets.top-up.store');

app/Models/Deposit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Deposit
 * @package App\Models
 *
 * @property User $user;
 * @property Wallet $wallet;
 * @property Transaction $transactions;
 */
class Deposit extends Model
{
    public $timestamps = false;
    public $dates      = ['created_at'];

    const MAX_ACCRUE_TIMES = 10;
    const DEFAULT_PERCENT  = 20;

    protected $fillable = [
        'invested',
        'percent',
        'active',
        'duration',
        'accrue_times',
        'created_at',
    ];

    protected $hidden = [];

    public static function scopeActive($q)
    {
        return $q->where('active', true);
    }

    public function isNotActive(): bool
    {
        return !$this->active;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function wallet()
    {
        return $this->belongsTo(Wallet::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function accruedAmount()
    {
        $amount = $this->transactions()->typeAccrue()->sum('amount');

        return $amount;
    }

    public function incrementAccrueTimes()
    {
        $this->accrue_times++;

        if ($this->accrue_times == $this::MAX_ACCRUE_TIMES) {
            $this->active = false;
        }
    }

    public function calculateAccrualAmount()
    {
        return $this->invested * ($this->percent / 100);
    }

}

app/Http/Controllers/DepositController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\Http\Requests\DepositCreateRequest;
use App\Models\Deposit;
use App\Models\Transaction;
use Illuminate\Support\Facades\DB;

class DepositController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $user     = Auth::user();
        $deposits = $user->deposits()->orderBy('created_at', 'desc')->get();

        return view('cabinet.deposits.index', compact('deposits'));
    }

    public function create()
    {
        return view('cabinet.deposits.create');
    }

    public function store(DepositCreateRequest $request)
    {
        $user                  = Auth::user();
        $user->wallet->balance -= $request->investing_amount;

        $deposit = Deposit::make([
            'invested' => $request->investing_amount,
            'percent'  => Deposit::DEFAULT_PERCENT,
            'active'   => true,
        ]);
        $deposit->user()->associate($user);
        $deposit->wallet()->associate($user->wallet);

        $transactionCreateDeposit = Transaction::make([
            'type'   => Transaction::TYPE_CREATE_DEPOSIT,
            'amount' => $request->investing_amount,
        ]);
        $transactionCreateDeposit->wallet()->associate($user->wallet);
        $transactionCreateDeposit->user()->associate($user);

        DB::transaction(function () use ($user, $deposit, $transactionCreateDeposit) {
            $user->wallet->save();
            $deposit->save();

            $transactionCreateDeposit->deposit()->associate($deposit)
                ->save();
        });

        return redirect()->route('deposits.index');
    }

}

resources/views/cabinet/deposits/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">

        <form method="POST" action="{{ route('deposits.store') }}">
          @csrf

          <div class="form-group row">
            <label for="investing_amount" class="col-md-4 col-form-label text-md-right">Investing amount (20 - 100)</label>

            <div class="col-md-6">
              <input id="investing_amount" type="number"
                     class="form-control @error('investing_amount') is-invalid @enderror" name="investing_amount"
                     value="{{ old('investing_amount') }}" required autocomplete="investing_amount" autofocus>
            </div>
          </div>

          <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Send
              </button>
            </div>
          </div>

        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/cabinet/deposits/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">

                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Сумма вклада</th>
                        <th scope="col">Процент</th>
                        <th scope="col">Количество текущих начислений</th>
                        <th scope="col">Сумма начислений</th>
                        <th scope="col">Статус депозита</th>
                        <th scope="col">Дата</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($deposits as $deposit)
                        <tr>
                            <th scope="row">{{ $deposit->id }}</th>
                            <td>{{ $deposit->invested }}</td>
                            <td>{{ $deposit->percent }} %</td>
                            <td>{{ $deposit->accrue_times }}</td>
                            <td>{{ $deposit->accruedAmount() }}</td>
                            <td>{{ $deposit->active ? 'active' : 'closed'}}</td>
                            <td>{{ $deposit->created_at }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
@endsection